services:
  - type: web
    name: drivelah-admin-bff
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health/live
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AI_AGENTS_API_URL
        sync: false
      - key: GOOGLE_CLIENT_ID  
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: INTERNAL_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://admin-controls.drivelah.sg,https://*.onrender.com
      - key: LOG_LEVEL
        value: info